version: '3'

services:
  web:
    build:
      context: backend/
      dockerfile: Dockerfile
    volumes:
      - .:/web
      - web_static_volume:/web/static
      - web_files_volume:/web/files
    restart: always
    ports:
      - "8000:8000"
    networks:
      - web_network
      - nginx_network
    depends_on:
      - db
  db:
    image: postgres:10
    container_name: db
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - db

volumes:
  db:
  web_static_volume:
  web_files_volume:
networks:
  db:
  nginx_network:
  web_network:
